
package gadak;

import gadak.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author szymon
 */
public class Gadak extends javax.swing.JFrame {
    private final int GRAMS = 3;
    private final String NazwaPliku = "src/gadak/Iliada.txt";
    
    private SlownikPrzejsc sp ;
    
    private void czatuj(){
        wyswietlacz.append("Ty: "+wejscie.getText()+"\n");
        wyswietlacz.append("- - - - - - - - - - -\n");
        wyswietlacz.append("Gadak: " + sp.Odpowiedz(wejscie.getText()) + "\n");
        wyswietlacz.append("- - - - - - - - - - -\n");
        wejscie.setText("");
    }
    
    public Gadak() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wyswietlacz = new javax.swing.JTextArea();
        wejscie = new javax.swing.JTextField();
        przycisk_wyslij = new javax.swing.JButton();
        przycisk_wczytaj = new javax.swing.JButton();
        label1 = new java.awt.Label();
        wejscie_slownik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAutoscrolls(true);
        jPanel1.setName("Gadak"); // NOI18N
        jPanel1.setOpaque(false);

        wyswietlacz.setEditable(false);
        wyswietlacz.setColumns(20);
        wyswietlacz.setRows(5);
        jScrollPane1.setViewportView(wyswietlacz);

        wejscie.setText("jTextField1");
        wejscie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wejscieKeyPressed(evt);
            }
        });

        przycisk_wyslij.setText("Wyslij!");
        przycisk_wyslij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_wyslijActionPerformed(evt);
            }
        });

        przycisk_wczytaj.setText("Wczytaj!");
        przycisk_wczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przycisk_wczytajActionPerformed(evt);
            }
        });

        label1.setText("Plik żródłowy");

        wejscie_slownik.setText("Plik źródłowy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(wejscie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(przycisk_wyslij, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wejscie_slownik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(przycisk_wczytaj)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(przycisk_wczytaj)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(wejscie_slownik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(przycisk_wyslij, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(wejscie))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void przycisk_wyslijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_wyslijActionPerformed
        czatuj();
    }//GEN-LAST:event_przycisk_wyslijActionPerformed
    private void wejscieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wejscieKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            czatuj();
        }
    }//GEN-LAST:event_wejscieKeyPressed

    private void przycisk_wczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przycisk_wczytajActionPerformed
        System.out.println(wejscie_slownik.getText());
        sp = new SlownikPrzejsc(GRAMS, wejscie_slownik.getText());
    }//GEN-LAST:event_przycisk_wczytajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gadak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gadak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gadak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gadak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gadak().setVisible(true);}  } );
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JButton przycisk_wczytaj;
    private javax.swing.JButton przycisk_wyslij;
    private javax.swing.JTextField wejscie;
    private javax.swing.JTextField wejscie_slownik;
    private javax.swing.JTextArea wyswietlacz;
    // End of variables declaration//GEN-END:variables
}
